[build]
builder = "NIXPACKS"
# Esto ejecutará "tsx script/build.ts" para crear la carpeta dist/
buildCommand = "npm run build"

[deploy]
# Esto ejecutará el servidor compilado desde dist/server/index.js
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
