[build]
builder = "RAILPACK"
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configuración correcta para multi-región en TOML
[deploy.multiRegionConfig.asia-southeast1-eqsg3a]
numReplicas = 1
