[build]
builder = "RAILPACK"   # fuerza Railpack como builder (ignora Dockerfile si existe)

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
useLegacyStacker = false

# Multi-regi√≥n correcta (usa la clave exacta "us-west2")
[deploy.multiRegionConfig."us-west2"]
numReplicas = 1

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10